name: Swift

on:
  push:
    branches: 
    - dev
    - feature/*
    - fix/*
    - refactor/*
  pull_request:
    branches:
    - dev
    - feature/*
    - fix/*
    - refactor/*

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        pod install --repo-update --clean-install --project-directory=MateRunner/
        xcodebuild test -workspace MateRunner/MateRunner.xcworkspace -scheme MateRunner -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.6'
